version: "3.3"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '1234:1234'
    volumes:
      - .:/usr/src/app
      - restake_node_modules:/usr/src/app/node_modules

volumes:
  restake_node_modules:
